dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - firefox
    packages:
      - firefox

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --progress=false --browsers=FirefoxHeadless
  - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
